### ISSUE TITLE
Extend the MoBileIPv6 to Proxy Mobile IPv6

### ISSUE THREAD

**Issue by Zhangronger** [manoj24rana/MobileIPv6#2]
Dear Mr.Rana,
   I'm currently working on a mobility management project which involves in Proxy Mobile IPv6(PMIPv6). I want to use the NS-3.26 version, but the PMIPv6 I've found from  https://github.com/G8XSU/ns3-pmipv6 is not compatible with NS-3.26, it's only compatible with NS-3.26. 
  I'm hoping I can implement the PMIPv6 based on your Mobile IPv6  work. But I'm not sure this will cost how much work, especially how long. Could you please give me some advice? I'd really appreciate it.
  
Rosey Zhang
South China University of Technology
Guangdong, Guangzhou

**Comment by manoj24rana** [comment]
First of all, I want to ask few questions:
what are you doing (B.Tech, Masters or Ph.D.)?
What do you want to do with MIPv6 or, PMIPv6?
Do you want to use it in LTE?

**Comment by Zhangronger** [comment]
Dear Mr.Rana,
  I'm working on my Master's  paper.
  I'm working on a mobility management based on PMIPv6 and MIH(Media Independent Handover).
  I think I have to use in LTE.
Thanks & Best Regards
Rosey Zhang

**Comment by Zhangronger** [comment]
I think I just know a little about code change within a module, bug tracking and new OOP design in ns-3. I've run a lot scripts in ns-3 and I have used the gdb command. And I'm not familiar with C++/C.....

**Comment by manoj24rana** [comment]
could you please come to Gtalk, if you don't mind? My id is manoj24.rana@gmail.com

**Comment by Zhangronger** [comment]
That'd be great. I'll find you on GTalk. Thanks a lot!

**Comment by Zhangronger** [comment]
Dear Mr.Rana, 
   There's no GTalk in China. May I discuss with you through Google Drive? I've sent you a message on Google Drive.  If you can contact me now through Google Drive. Please let me know . My Gmail is roseyzhr@gamil.com. Thanks a lot~~~

**Comment by manoj24rana** [comment]
You just ON your Gmail, you will see a request, otherwise, go to Skype. My id is +91-9681098836

**Comment by Zhangronger** [comment]
I'm sorry , there's so many limitations in China. It'd take a while for me to get online on Skype. I'll come back later to get in touch with you on Skype If the network works fine. This is very nice of you. Thank you so much.

**Comment by Zhangronger** [comment]
Dear Mr.Rana,
  I'm so sorry that I couldn't find you on Skype through the ID you gave me. Could please find me on Skype? My Skype ID is +86 15625064706. Thanks a lot.

**Comment by manoj24rana** [comment]
Just wait a little bit

**Comment by Zhangronger** [comment]
Sorry...There's nothing on my Skype. Maybe GMail is the best way for me to get in touch with you. Do you have WeChat? If you have WeChat, that'd be wonderful since we can chat through WeChat, the IM developed by Tencent.  My WeChat ID is my phone +86 156 2506 4706

**Comment by manoj24rana** [comment]
Better, we start here.

**Comment by manoj24rana** [comment]
Are you there?
