### ISSUE TITLE
To upgrade this repo to Proxy mobile IPV6 

### ISSUE THREAD

**Issue by Zhangronger** [manoj24rana/MobileIPv6#3]
Dear Mr.Rana,
   It's Rosey again. I have so many troubles in porting Mr.Choi code of PMIPv6(based on ns-3.29) to NS-.26. 
   I'm hoping there's another way for me to develop pmipv6 in NS-3.26.
   Is it possible for me to upgrade your work of MIPv6 to PMIPv6 and how long do you think it will take?
   Could you please kindly help me out here?
   Thanks a lot.

**Comment by Zhangronger** [comment]
Dear Mr.Rana,

 I'm thinking develop PMIPv6 based on your MIPv6 repo. I really hope that you can give me some advice on this.

**Comment by manoj24rana** [comment]
You can, but, I'm really very busy. You can go through the documentation of the work.

**Comment by Zhangronger** [comment]
Dear Mr.Rana,
  I've noticed that you have developed HMIPv6 based on your work of MIPv6 in NS3. Is that possible that you would like to share your work of the implemented HMIPv6 in NS3 based on MIPv6?
  It'd be of much help for my research and I'd really appreciate it.
   Thanks a lot!
Best Regards
Rosey Zhang
Email: roseyzhr@gmail.com
